### ISSUE TITLE
中断服务例程 xSemaphoreGiveFromISR crash 问题

### ISSUE THREAD

**Issue by BlueSkyai** [espressif/esp-aliyun#10]
@ustccw
你好，我在usermain.c中新建了一个二值信号量xsemaphore，调用了uart_int_new()，然后在uart.c的中断函数中新建了xsemaphoreGiveFromISR（），因为这一点，系统出现了故障，之前用队列的时候在中断这里也出现了问题，不知道什么原因，中断这里应怎么添加类似的程序呢？
![xsemaphore](https://user-images.githubusercontent.com/31559830/34968392-f45f441c-faa3-11e7-94b9-0f4712de1bf8.png)
![mistake](https://user-images.githubusercontent.com/31559830/34968400-f9f6526c-faa3-11e7-9903-f9e4402ee7e5.png)

**Comment by ustccw** [comment]
@BlueSkyai 请参考《FREERTOS 实时内核实用指南》使用。
如果你有疑问，请附上完整的测试程序，测试步骤和测试环境，谢谢。

**Comment by BlueSkyai** [comment]
@ustccw 谢谢，我一些会儿上传

**Comment by BlueSkyai** [comment]
@ustccw 你好，程序很简单，就是首先创建二值向量，然后在驱动uart.c的串口中断中，当有数据从串口0输入就发出这个二值向量信号，我编译通过了，但是下载后出现了乱码，而且我试下来，可以确定乱码原因是由于串口中断这里添加了发出二值向量的程序，从程序上我看不出哪里有错误，附上代
[test.zip](https://github.com/espressif/esp8266-aliyun/files/1634261/test.zip)
码

**Comment by BlueSkyai** [comment]
@ustccw  二值向量创建成功了，可以看到打印successful，但是串口中断的简单程序导致了乱码，程序是按照freeRTOS内核说明去写的
![init](https://user-images.githubusercontent.com/31559830/34980327-1c076306-fadf-11e7-9efd-28c41b5bea62.png)

**Comment by BlueSkyai** [comment]
@ustccw test文件夹里的内容您可直接替换到库程序里，然后MQTT的部分可以先屏蔽
#if 0
    switch (DEFAULT_TASK_MODE) {
    case MQTT_TASK:
        xTaskCreate(mqtt_proc, "mqtt_proc", 2048, NULL, 5, NULL);
        os_printf("\nMQTT task started...\n");
        break;

    case LOCAL_OTA_TASK:
        xTaskCreate(local_ota_proc, "local_ota_proc", 2048, NULL, 5, NULL);
        os_printf("\nlocal OTA task started...\n");
        break;

    case REMOTE_OTA_TASK:
        xTaskCreate(remote_ota_proc, "ota_proc", 2048, NULL, 5, NULL);
        os_printf("\nremote OTA task started...\n");
        break;

    default:
        os_printf("task mode error happend!\n");
        break;
    }
#endif

**Comment by ustccw** [comment]
@BlueSkyai 
不清楚你是不是编译了 driver。也不知道你其他地方改了啥。
我把自己成功的代码上传了，见 [云盘](https://pan.baidu.com/s/1jJnyaOm)

成功log如下：
![_004](https://user-images.githubusercontent.com/24221485/34983477-a14fc90a-fae8-11e7-8ae7-1eb6d8cbe79f.png)

**Comment by BlueSkyai** [comment]
@ustccw 但是不编译driver，用串口0就接受不到数据，也就是无法进入到uart0 rx intr handler，把接受到的数据打印出来，编译了driver就有乱码了

**Comment by BlueSkyai** [comment]
@ustccw 按理编译了driver程序不应该乱啊，那样串口数据就无法处理了

**Comment by ustccw** [comment]
@BlueSkyai 你的环境配置可能有些问题，用我云盘分享的代码就可以了。

**Comment by BlueSkyai** [comment]
@ustccw 你的log里打印了tout ，是从串口0输入了数据，数据没有打印出来啊

**Comment by BlueSkyai** [comment]
@ustccw 你可以试一下编译driver，然后从串口0输入数据，就能有显示了，但是这样如果把freeRTOS的内容加入进去的话会产生问题

**Comment by ustccw** [comment]
@BlueSkyai 我提供的代码就是从串口 0 输入数据啊。我连续输入了 三个1啊！不然怎么会触发三次中断处理。

**Comment by BlueSkyai** [comment]
@ustccw printf("tout\r\n");
            fifo_len = (READ_PERI_REG(UART_STATUS(UART0)) >> UART_RXFIFO_CNT_S)&UART_RXFIFO_CNT;
            buf_idx = 0;

            while (buf_idx < fifo_len) {
                uart_tx_one_char(UART0, READ_PERI_REG(UART_FIFO(UART0)) & 0xFF);
                buf_idx++;
            }
这段代码的uart_tx_one_char(UART0, READ_PERI_REG(UART_FIFO(UART0)) & 0xFF);就是打印数据了

**Comment by BlueSkyai** [comment]
@ustccw 不信你可以编译一下driver看有没有输出呢

**Comment by ustccw** [comment]
@BlueSkyai 不明白你的意思。

**Comment by BlueSkyai** [comment]
@ustccw 那请问输入的三个1哪里去了呢

**Comment by ustccw** [comment]
三个1就是输出啊，我的串口工具没有回显。

**Comment by BlueSkyai** [comment]
@ustccw 你好，其实我测过，保证有回显

**Comment by ustccw** [comment]
@BlueSkyai 
-e 代表回显。
我输入了 tellme.

![_006](https://user-images.githubusercontent.com/24221485/35021261-0e7ef654-fb6b-11e7-8e26-f57c9b15792c.png)

当没有做过深入的测试和了解，请不要轻易说`保证`

**Comment by BlueSkyai** [comment]
@ustccw 我只不过是偶尔看到了，并不确定原因，请问有进展了吗？

**Comment by BlueSkyai** [comment]
@ustccw 附上编译driver之后，其他cpu向8266发送内容，tout字符后面乱码的内容就是数据了
![1](https://user-images.githubusercontent.com/31559830/35095398-436ad6a8-fc83-11e7-97d5-70c1a45deb1b.png)

**Comment by BlueSkyai** [comment]
@ustccw 其实就是01H 02H 03H 04H，重复发送重复接受到了
while (buf_idx < fifo_len) {
            uart_tx_one_char(UART  **1**  , READ_PERI_REG(UART_FIFO(UART0)) & 0xFF);
            buf_idx++;
        }

**Comment by BlueSkyai** [comment]
@ustccw 几个办法都试过了

**Comment by ustccw** [comment]
@BlueSkyai 本 issue 是解决 crash 问题的，如果觉得驱动有 bug,可通过官网来获取更快的技术支持。[链接](http://espressif.com/zh-hans/company/contact-extra/technical-inquiries-software)

**Comment by BlueSkyai** [comment]
@ustccw 感谢你的耐心支持！
