### ISSUE TITLE
error code  -33

### ISSUE THREAD

**Issue by weigtman** [espressif/esp-aliyun#101]
有大家遇到 -33 的连接错误码吗？感谢

**Comment by wjj-chn** [comment]
你好，可以更详细的描述以下信息吗？
ESP 芯片 
ESP 模组名称 
ESP SDK 版本号  
您参考的文档链接  
问题复现步骤 
Log

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 esp-aliyun release v2.0 测试。
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
