### ISSUE TITLE
/bin/sh: 1: cd: can't cd to /home/linux/iot-hub/esp-aliyun/iotkit-embedded

### ISSUE THREAD

**Issue by atoyx** [espressif/esp-aliyun#102]
/home/linux/iot-hub/esp-aliyun/platform/hal/os/espressif/HAL_AWSS_espressif.c:23:24: fatal error: iot_import.h: No such file or directory
编译demo的时候就找不到iot_import.h这个文件

**Comment by atoyx** [comment]
已解决  git clone 未加--recusive参数，导致iot_kitembeded文件不能cd进入。
另如使用8266芯片，IDF_PATH应该为所下载的ESP8266_RTOS所在路径。
flash选择1MB会出现错误，选择大点解决

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 esp-aliyun release v2.0 测试。
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
