### ISSUE TITLE
dm fota doesn't work

### ISSUE THREAD

**Issue by unone1** [espressif/esp-aliyun#103]
Example smart_light, fota by dm, ssl connection failed, wolfssl error -416:

[1;36m[dbg] CoAPRequestMessage_handle(730): Request path is /sys/device/info/get

[0m[1;36m[dbg] CoAPRequestMessage_handle(730): Request path is /sys/device/info/get

[0m[1;36m[dbg] iotx_mc_cycle(1809): PUBLISH

[0m[1;36m[dbg] iotx_mc_handle_recv_PUBLISH(1566):         Packet Ident : 00000000

[0m[1;36m[dbg] iotx_mc_handle_recv_PUBLISH(1567):         Topic Length : 52

[0m[1;36m[dbg] iotx_mc_handle_recv_PUBLISH(1571):           Topic Name : /ota/device/upgrade/a1Ex7pnqO8n/GZWmYRzBwUJSqFtzQbsI

[0m[1;36m[dbg] iotx_mc_handle_recv_PUBLISH(1574):     Payload Len/Room : 370 / 1143

[0m[1;36m[dbg] iotx_mc_handle_recv_PUBLISH(1575):       Receive Buflen : 1200

[0m[1;36m[dbg] iotx_mc_handle_recv_PUBLISH(1586): delivering msg ...

[0m[1;36m[dbg] iotx_mc_deliver_message(1287): topic be matched

[0m[1;36m[dbg] otamqtt_UpgrageCb(107): topic=/ota/device/upgrade/a1Ex7pnqO8n/GZWmYRzBwUJSqFtzQbsI

[0m[1;36m[dbg] otamqtt_UpgrageCb(108): len=370, topic_msg={"code":"1000","data":{"size":572048,"sign":"8d61545e8dcd3664827ef9eb8b5a2aaa","version":"2.0","url":"https://iotx-ota.oss-cn-shanghai.aliyuncs.com/AfBbZZ2Mj6_1556524106668.bin?Expires=1557286171&OSSAccessKeyId=cS8uRRy54RszYWna&Signatur ...

[0m[1;36m[dbg] otamqtt_UpgrageCb(123): receive device upgrade

[0m[1;36m[dbg] dm_fota_status_check(165): Fota Status Check

[0m[1;33m[inf] _dm_fota_send_new_config_to_user(50): Send To User: {"version":"2.0"}

[0m[1;36m[dbg] dm_ipc_msg_insert(87): dm msg list size: 0, max size: 50

[0m[1;33m[inf] _iotx_linkkit_event_callback(223): Receive Message Type: 40

[0m[1;33m[inf] _iotx_linkkit_event_callback(225): Receive Message: {"version":"2.0"}

[0m[1;36m[dbg] _iotx_linkkit_event_callback(630): Current Firmware Version: 2.0

[0muser_fota_event_handler|531 :: New Firmware Version: 2.0

[0;32mI (1825895) HAL-OS: Starting ESP-OTA...[0m
[0;32mI (1825905) HAL-OS: Running partition type 0 subtype 16 (offset 0x00010000)[0m
[0;32mI (1825915) HAL-OS: Writing to partition subtype 17 at offset 0x110000[0m
[0;32mI (1828325) HAL-OS: esp_ota_begin succeeded[0m
[1;33m[inf] httpclient_common(814): host: 'iotx-ota.oss-cn-shanghai.aliyuncs.com', port: 443

[0m[0;32mI (1828855) in: Creat socket ...[0m
[0;32mI (1828855) in: reuse addr OK:3[0m
[0;32mI (1828855) in: establish tcp connection with server(host=iotx-ota.oss-cn-shanghai.aliyuncs.com port=443)[0m
[0;32mI (1828905) in: OK[0m
[0;32mI (1828905) in: ssl context already initialized 
[0m
[0;31mE (1829055) in: failed create ssl connection:-416 
[0m
[1;31m[err] httpclient_conn(67): establish connection failed

[0m[1;31m[err] httpclient_common(825): httpclient_connect is error, ret = -8

[0m[1;33m[inf] httpclient_close(803): client disconnected

[0m[1;31m[err] ofc_Fetch(70): fetch firmware failed

[0m[1;31m[err] IOT_OTA_FetchYield(700): Fetch firmware failed

[0m[0;32mI (1829095) HAL-OS: Stop ESP-OTA...[0m
[0;31mE (1829095) HAL-OS: esp_ota_end failed![0m
[1;36m[dbg] MQTTKeepalive(319): len = MQTTSerialize_pingreq() = 2

[0m[1;33m[inf] iotx_mc_keepalive_sub(2987): send MQTT ping...

[0m[1;33m[inf] iotx_mc_cycle(1828): receive ping response!

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 esp-aliyun release v2.0 测试。
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
