### ISSUE TITLE
*SOMETIMES* main task blocked while calling ssl_connect

### ISSUE THREAD

**Issue by unone1** [espressif/esp-aliyun#104]
In the testing for wifi connection breaking & reconnecting, the ssl reconnecting will take about 20 seconds for the failed case normally, *SOMETIMES* the reconnecting blocks the main task for 1 or 2 or more hours. The block call is ssl_connect(wolfssl), file HAL_TLS_openssl.c, in the funtion ssl_establish.

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 esp-aliyun release v2.0 测试。
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
