### ISSUE TITLE
大概什么时间能放出ESP[平台的阿里云V3.0.1版本呢?

### ISSUE THREAD

**Issue by Shaco-Ma** [espressif/esp-aliyun#112]

**Comment by jorislee** [comment]
您可以先尝试使用分支 featrue/update_3.0.1_for_mesh.
该分支扩展了部分 mesh 相关的功能.
若不使用 mesh, 也是可以直接在 ESP 平台编译运行的.
如果使用中遇到问题,希望可以反馈.

**Comment by Eavo** [comment]
v3.0.1 正在测试中，预计八月中上旬 release。

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 esp-aliyun release v2.0 测试。
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
谢谢。
