### ISSUE TITLE
HAL_SemaphoreWait等信号异常

### ISSUE THREAD

**Issue by wanghui0574xs** [espressif/esp-aliyun#113]
HAL_OS_espressif.c
HAL_SemaphoreCreate使用了freertos的互斥信号量xSemaphoreCreateMutex 
创建后, 直接调用HAL_SemaphoreWait 等待, 会理解获得.不需要HAL_SemaphorePost.

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 esp-aliyun release v2.0 测试。
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
