### ISSUE TITLE
请问Smart Light  现在是否已经支持esp8266了？

### ISSUE THREAD

**Issue by liubaiwu** [espressif/esp-aliyun#114]
请问esp8266 现在使用阿里云 云只能app 配网 是否已经支持 ？

**Comment by liubaiwu** [comment]
是否支持请给个答复，如果不支持我们好更换其他芯片。如果支持，大概什么时候能支持。

**Comment by wjj-chn** [comment]
@liubaiwu
master 分支的 Smart Light 示例已支持。

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 esp-aliyun release v2.0 测试。
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
