### ISSUE TITLE
阿里云c-sdk已经更新到3.0.1好几个月了，这边是否有更新计划？

### ISSUE THREAD

**Issue by simonliu009** [espressif/esp-aliyun#115]
阿里云c-sdk在3月份已经更新到3.0.1，需要实现的函数都统一放在一个文件里面了，更方便二次开发。
建议跟进更新。
[User_interface_changes · Wikis · edward.yangx / public-docs · CODE](https://code.aliyun.com/edward.yangx/public-docs/wikis/user-guide/linkkit/User_Interface_Changes#%E6%96%B0%E5%A2%9E%E7%9A%84%E5%8A%9F%E8%83%BD%E7%82%B9%E5%92%8C%E6%8E%A5%E5%8F%A3)

**Comment by wzbhbb** [comment]
遇到什么问题了吗？

**Comment by simonliu009** [comment]
我是计划使用阿里云，先是尝试了alios things一段时间后发现问题比较多，所以决定回到ESP8266 freeRTOS sdk+ 阿里云c-sdk开发。由于c-sdk 2.3也只是浅尝辄止，而c-sdk 3.0.1在代码结构上也有比较大的调整，所以只是希望在项目开始前能有一个正式的release。

**Comment by Eavo** [comment]
v3.0.1 正在测试中，预计八月中旬将 release。

**Comment by wzbhbb** [comment]
今天我的一个客户测试创建的设备都走的新接口方式，就是所谓的物模型，我刚基于2.3 C-SDK开发的应用，现在连接不上了~~~~~~ @Eavo

**Comment by simonliu009** [comment]
> 今天我的一个客户测试创建的设备都走的新接口方式，就是所谓的物模型，我刚基于2.3 C-SDK开发的应用，现在连接不上了~~~~~~ @Eavo

新的sdk需要物模型吗？在alios things rel2.1.0里面上报已经不要求物模型了，任意属性使用json上报就可以了。rel2.1.0对应的c-sdk应该就是3.0.1。

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 release v2.0 测试，谢谢。

**Comment by 27-301** [comment]
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
