### ISSUE TITLE
设备和控制台MQTT消息对接

### ISSUE THREAD

**Issue by BlueSkyai** [espressif/esp-aliyun#12]
@ustccw 你好，设备发送消息到控制台显示no authorization，控制台发送消息到设备显示topic message arrived but without any related handle，发送的消息是有一个结构体，但是控制台发送的就只是字符串，不知道该如何对接呢？你的案例中8266和控制台能够成功对接。

**Comment by ustccw** [comment]
@BlueSkyai 这是阿里的 IoT 套件和阿里云控制台之间的交互。你可以向阿里方面详细咨询里面细节。

**Comment by BlueSkyai** [comment]
@ustccw 好了，我有个地方马虎了，谢谢~~

**Comment by rousir** [comment]
@BlueSkyai 你好，我编译示例也遇到了同样的问题，是那儿不对呢
