### ISSUE TITLE
Demo esp-aliyun/examples/solutions/smart_light 阿里云在线调试可以设置但无法获取问题

### ISSUE THREAD

**Issue by qiufeng81888** [espressif/esp-aliyun#122]
Hi esp-aliyun,
您好！
我在使用 Demo esp-aliyun/examples/solutions/smart_ligh ,配合阿里云做在线调试，发现可以设置，但无法获取，什么原因？
如下:
阿里云在线调试
主灯开关 方法 设置
{
  "LightSwitch": 0
}
设置有效。user_property_set_event_handler 有相应的动作发生.

主灯开关 方法 获取
获取无效。 没有反应。user_property_get_event_handler 无相应的动作。

Thks & BR!
Qiufenghua

**Comment by ljy770** [comment]
按照阿里云手册说明，
https://code.aliyun.com/edward.yangx/public-docs/wikis/user-guide/linkkit/Cloud_Interface
设备属性获取：由于目前云端会直接从自己的设备缓存中返回属性值给用户, 此接口暂时无效

**Comment by wjj-chn** [comment]
你好，请问问题目前解决了吗？

**Comment by qiufeng81888** [comment]
Hi esp-aliyun,
您好！
收到，明白了，谢谢！

Thks & BR!
Qiufenghua
