### ISSUE TITLE
rtos已经发布3.2版本的了，能否做一个迁移Smart Light 到rtos的事例。

### ISSUE THREAD

**Issue by liubaiwu** [espressif/esp-aliyun#123]
想要把Smart Light  迁移到最新版本的rtos SDK里面 是否能做一个迁移介绍，指导下如何进行迁移。

**Comment by 27-301** [comment]
请使用基于 iotkit-embedded v3.0.1 重新适配的 release v2.0 测试，谢谢。

**Comment by 27-301** [comment]
相关文档已更新，请参考。建议重新 clone 一下 esp-aliyun。
如在新版本上遇到问题，请重新提交 issue。
谢谢。
