### ISSUE TITLE
smart_light：微信小程序能否实现app功能？

### ISSUE THREAD

**Issue by liupenghui0313** [espressif/esp-aliyun#127]
请问esp8266使用smart_light 例程，能否使用微信小程序替代app的配网和通讯控制的功能？

**Comment by ljy770** [comment]
您好，目前不支持使用微信小程序替代app的配网和通讯控制的功能，只有APP形式。
阿里云生活物联网平台为开发者提供了2种APP形式，开发者可以根据自己的情况选择，https://living.aliyun.com/doc?spm=a2c9o.12549863.index_left.3.4e9d7946vTP0jy#muti-app.html

**Comment by liupenghui0313** [comment]
你好，如果想通过微信小程序实现对esp8266的控制，请问有相关的示例吗？
谢谢！

**Comment by ljy770** [comment]
目前没有，aliyun 方面也未看到提供示例。

**Comment by liupenghui0313** [comment]
好的，感谢
