### ISSUE TITLE
请问配网方式支持零配和蓝牙配网吗？

### ISSUE THREAD

**Issue by PeterSun01** [espressif/esp-aliyun#132]
阿里云配网方式目前支持零配和蓝牙配网，请问目前支持吗？是否有相关的demo?

**Comment by 27-301** [comment]
可以支持零配，蓝牙暂时不支持，在计划中。
可以使用 examples/solutions/smart_light，直接支持天猫精灵配网，暂时先用 esp8266 测，esp32 还没做过测试。
