### ISSUE TITLE
请问ESP32内部有SSID和PWD信息，设备拿到了一个新的WIFI环境，如何重新配网

### ISSUE THREAD

**Issue by PeterSun01** [espressif/esp-aliyun#134]
## 1. 开发环境

- 模组或开发板：ESP32 WROOM
- esp-aliyun 版本（``git rev-parse --short HEAD`` 来获取 commit id）：
- ESP8266_RTOS_SDK 版本（``git rev-parse --short HEAD`` 来获取 commit id）：
- ESP-IDF 版本（``git rev-parse --short HEAD`` 来获取 commit id）：

## 2. 问题描述

1、请问设备初次配网后，再次上电则按内部保存的SSID连接，如设备拿到了一个新的WIFI环境，如何清空内部的ssid，进入重新配网？
2、另外阿里云飞燕平台，在配网时APP有提示确认指示灯闪烁，在smartlight等其他demo中这个配网指示灯有相关设置吗？

### 2.1 复现步骤

无

### 2.2 复现问题的代码

无

## 3. 调试 Logs

无
## 4. 其他项

无

**Comment by 27-301** [comment]
1. smart_light 中是有个 factory restore 功能的，对于 light 这类无实体按键的设备，是通过下电重启的方式来让设备恢复出厂设置，当前是下电上电 5 次恢复，如果你有实体按键，可以参考 factory_restore.c 做复位；
2. 当前 demo 中没有指示灯功能；
