### ISSUE TITLE
master版本和V2.0版本在哪里配置WIFI_SSID和WIFI_PASSWORD?

### ISSUE THREAD

**Issue by hantown** [espressif/esp-aliyun#137]
## 1. 开发环境

- 模组或开发板：
- esp-aliyun 版本（``git rev-parse --short HEAD`` 来获取 commit id）：V2.0和master版本都试过
- ESP8266_RTOS_SDK 版本（``git rev-parse --short HEAD`` 来获取 commit id）：V3.2
- ESP-IDF 版本（``git rev-parse --short HEAD`` 来获取 commit id）：d7960baa

## 2. 问题描述

编译examples/solutions/smart_light，make menuconfig出来的菜单里面没有出现配置WIFI_SSID和WIFI_PASSWORD的页面。在项目文件夹下面搜索WIFI_SSID和WIFI_PASSORD关键字也没有搜索出来。
master和V2.0版本都是一样。

### 2.1 复现步骤
无

### 2.2 复现问题的代码

无。

## 3. 调试 Logs
ESP8266上电后从log里面看，模块在不断的扫描各个所能找到的WIFI路由器，但是没密码，连不上。
[0m[1;31m[crt] awss_save_apinfo(271): [1] ssid:, mac:f8c39ed5e835, chn:6, rssi:-71, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [2] ssid:, mac:f8c39ed5e831, chn:6, rssi:-71, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [3] ssid:lifesense106, mac:70d379dd4080, chn:6, rssi:-65, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [4] ssid:Transtek-work, mac:70d379dd4081, chn:6, rssi:-64, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [5] ssid:lifesense106, mac:d42c44d93d00, chn:1, rssi:-90, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [6] ssid:Transtek-work, mac:d42c44d93d01, chn:1, rssi:-90, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [7] ssid:Transtek-phone, mac:d42c44d93d03, chn:1, rssi:-91, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [8] ssid:lifesense106, mac:d42c44d939e0, chn:1, rssi:-77, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [9] ssid:Transtek-work, mac:d42c44d939e1, chn:1, rssi:-76, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [10] ssid:Transtek-phone, mac:d42c44d939e3, chn:1, rssi:-74, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [11] ssid:Transtek-guest, mac:d42c44d939e4, chn:1, rssi:-75, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [12] ssid:lifesense106, mac:70d379ddd280, chn:1, rssi:-81, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [13] ssid:Transtek-work, mac:70d379ddd281, chn:1, rssi:-82, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [14] ssid:Transtek-phone, mac:70d379ddd283, chn:1, rssi:-81, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [15] ssid:Transtek-guest, mac:70d379ddd284, chn:1, rssi:-82, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [16] ssid:lifesense106, mac:d42c44d921a0, chn:1, rssi:-92, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [17] ssid:Transtek-guest, mac:d42c44d921a4, chn:1, rssi:-93, adha:0
[0m
[13:35:00.451]收←◆[1;31m[crt] awss_save_apinfo(271): [18] ssid:ceshizhonxin, mac:34bdf951c9e8, chn:1, rssi:-95, adha:0
[0m
[13:35:00.491]收←◆[1;31m[crt] awss_save_apinfo(271): [19] ssid:Transtek-guest, mac:d42c44d93d04, chn:1, rssi:-89, adha:0
[0m
[13:35:00.518]收←◆[1;31m[crt] awss_save_apinfo(271): [20] ssid:Transtek-work, mac:d42c44d921a1, chn:1, rssi:-91, adha:0
[0m[1;31m[crt] awss_save_apinfo(271): [21] ssid:Transtek-phone, mac:d42c44d921a3, chn:1, rssi:-91, adha:0
[0m
[13:35:00.992]收←◆[1;31m[crt] awss_save_apinfo(271): [22] ssid:ChinaNet-qCfj, mac:d8325a223737, chn:3, rssi:-87, adha:0

## 4. 其他项
无

**Comment by ljy770** [comment]
您当前使用的 smart_light 示例,不需要配置 WIFI_SSID和WIFI_PASSWORD, 需要用 云智能 APP 进行配网,具体请参考示例下的 readme.  
比如 example/mqtt 示例由于没有配网, 需要配置 WIFI_SSID和WIFI_PASSWORD.
具体每个示例有所不同,参考每个示例下的 readme.
