### ISSUE TITLE
配置3元组，从阿里云获取的数据名称与CSV上面的不一致，咋整？

### ISSUE THREAD

**Issue by hantown** [espressif/esp-aliyun#140]
## 1. 开发环境

- 模组或开发板：
- esp-aliyun 版本（``git rev-parse --short HEAD`` 来获取 commit id）：c5a1728
- ESP8266_RTOS_SDK 版本（``git rev-parse --short HEAD`` 来获取 commit id）：d7960baa
- ESP-IDF 版本（``git rev-parse --short HEAD`` 来获取 commit id）：d7960baa

## 2. 问题描述

配置3元组，从阿里云获取的数据名称与CSV上面的对应不上，要怎么弄？
![20190920110206](https://user-images.githubusercontent.com/11001695/65296231-60601e00-db96-11e9-9e85-c9f6d7ba5680.png)

![20190920105803](https://user-images.githubusercontent.com/11001695/65296024-c4361700-db95-11e9-8365-93bc732e3f64.png)

### 2.1 复现步骤

无
### 2.2 复现问题的代码

无

## 3. 调试 Logs
无

## 4. 其他项

无

**Comment by ljy770** [comment]
/home/lijingyi/esp/esp-aliyun-master/esp-aliyun/examples/solutions/smart_light/_static/p3.png

**Comment by ljy770** [comment]
![p3](https://user-images.githubusercontent.com/53285923/65297085-46740a80-db99-11e9-845f-7ae282dff94e.png)

**Comment by hantown** [comment]
好的，谢谢
