### ISSUE TITLE
如何与ESP8266_RTOS_SDK合并

### ISSUE THREAD

**Issue by angle600** [espressif/esp-aliyun#142]
这堆代码没有makefile文件，也没有CMakeLists.txt，请问应该如何合并到ESP8266_RTOS_SDK中？

**Comment by xuhongv** [comment]
- 参考下这个博文：
- esp8266 sdk 直连接入阿里云物联网平台，实现天猫精灵找队友零配网功能和语音控制； - 徐宏的博客。 - CSDN博客 https://blog.csdn.net/xh870189248/article/details/101448052

**Comment by ljy770** [comment]
> 这堆代码没有makefile文件，也没有CMakeLists.txt，请问应该如何合并到ESP8266_RTOS_SDK中？

不需要合并，在 monitor 中指定 IDF_PATH 的路径即可。例如
`export IDF_PATH=~/esp/ESP8266_RTOS_SDK`

**Comment by angle600** [comment]
我用id

> > 这堆代码没有makefile文件，也没有CMakeLists.txt，请问应该如何合并到ESP8266_RTOS_SDK中？
> 
> 不需要合并，在 monitor 中指定 IDF_PATH 的路径即可。例如
> `export IDF_PATH=~/esp/ESP8266_RTOS_SDK`

我用idy.py build来生成，为什么不可以呢？难道一定要用linux?

**Comment by angle600** [comment]
在windows下用msys32成功make
