### ISSUE TITLE
solutions\smart_light如何触发进入配网？

### ISSUE THREAD

**Issue by angle600** [espressif/esp-aliyun#143]
solutions\smart_light如何触发进入配网？芯片上电后不断打印如下信息，对天猫精灵音箱说“天猫精灵找队友”，没有配到网络

[1;31m[crt] aws_switch_channel(166): chan 13

[0m[1;31m[crt] aws_switch_channel(166): chan 1

[0m[1;31m[crt] aws_switch_channel(166): chan 2

[0m[1;31m[crt] awss_save_apinfo(271): [33] ssid:ChinaNet-eq8y, mac:e09796e0cb3c, chn:2, rssi:-95, adha:0

[0m[1;31m[crt] aws_switch_channel(166): chan 3

[0m[1;31m[crt] aws_switch_channel(166): chan 6

[0m[1;31m[crt] aws_switch_channel(166): chan 7

[0m[1;31m[crt] aws_switch_channel(166): chan 8

[0m[1;31m[crt] aws_switch_channel(166): chan 9

[0m[1;31m[crt] aws_switch_channel(166): chan 10

[0m[1;31m[crt] aws_switch_channel(166): chan 11

[0m[1;31m[crt] aws_switch_channel(166): chan 12

[0m[1;31m[crt] aws_switch_channel(166): chan 13

[0m[1;31m[crt] aws_switch_channel(166): chan 1

[0m[1;31m[crt] aws_switch_channel(166): chan 6

[0m[1;31m[crt] aws_switch_channel(166): chan 11

[0m[1;31m[crt] aws_switch_channel(166): chan 1

[0m[1;31m[crt] aws_switch_channel(166): chan 2

[0m[1;31m[crt] aws_switch_channel(166): chan 3

[0m[1;31m[crt] aws_switch_channel(166): chan 4

[0m[1;31m[crt] aws_switch_channel(166): chan 5

[0m[1;31m[crt] aws_switch_channel(166): chan 6

[0m[1;31m[crt] aws_switch_channel(166): chan 7

[0m[1;31m[crt] aws_switch_channel(166): chan 8

[0m[1;31m[crt] aws_switch_channel(166): chan 9

[0m[1;31m[crt] aws_switch_channel(166): chan 10

[0m[1;31m[crt] aws_switch_channel(166): chan 11

**Comment by ljy770** [comment]
天猫精灵配网，可以对天猫精灵说“发现设备”
一键配网，可以通过云智能 APP，国内用户版，下载链接：https://living.aliyun.com/doc#muti-app.html

**Comment by angle600** [comment]
这个设备上电后不断的打印.[0m.[1;31m[crt] aws_switch_channel(166):，用天猫精灵配置不了网络，用手机软件IOT_Espressif_EspTouch也配置不了，是什么原因呢？

.[0;32mI (50) boot: ESP-IDF v3.2-22-gcdcfbee 2nd stage bootloader.[0m
.[0;32mI (50) boot: compile time 23:57:34.[0m
.[0;32mI (50) boot: SPI Speed      : 40MHz.[0m
.[0;32mI (54) boot: SPI Mode       : DOUT.[0m
.[0;32mI (58) boot: SPI Flash Size : 4MB.[0m
.[0;32mI (62) boot: Partition Table:.[0m
.[0;32mI (65) boot: ## Label            Usage          Type ST Offset   Length.[0m
.[0;32mI (73) boot:  0 nvs              WiFi data        01 02 00009000 00004000.[0m
.[0;32mI (80) boot:  1 otadata          OTA data         01 00 0000d000 00002000.[0m
.[0;32mI (88) boot:  2 phy_init         RF data          01 01 0000f000 00001000.[0m
.[0;32mI (95) boot:  3 ota_0            OTA app          00 10 00010000 000f0000.[0m
.[0;32mI (103) boot:  4 fctry            WiFi data        01 02 00100000 00004000.[0m
.[0;32mI (110) boot:  5 ota_1            OTA app          00 11 00110000 000f0000.[0m
.[0;32mI (118) boot: End of partition table.[0m
.[0;32mI (122) boot: No factory image, trying OTA 0.[0m
.[0;32mI (127) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0xac08c (704652) map.[0m
.[0;32mI (445) esp_image: segment 1: paddr=0x000bc0a4 vaddr=0x3ffe8000 size=0x00828 (  2088) load.[0m
.[0;32mI (446) esp_image: segment 2: paddr=0x000bc8d4 vaddr=0x3ffe8828 size=0x0019c (   412) load.[0m
.[0;32mI (452) esp_image: segment 3: paddr=0x000bca78 vaddr=0x40100000 size=0x06834 ( 26676) load.[0m
.[0;32mI (472) boot: Loaded app from partition at offset 0x10000.[0m
.[0;32mI (521) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE.[0m
.[0;32mI (531) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE.[0m
,é§vî.[0;32mI (701) phy_init: phy ver: 1055_13.[0m
.[0;32mI (711) reset_reason: RTC reset 2 wakeup 0 store 0, reason is 2.[0m
.[0;33mW (711) wrapper_kv: nvs get blob q_rt failed with 1102.[0m
.[0;32mI (721) factory_rst: quick reboot times 1, don't need to restore.[0m
.[0;32mI (721) gpio: GPIO[0]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 .[0m
.[0;32mI (731) gpio: GPIO[2]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 .[0m
.[0;32mI (741) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 .[0m
.[0;32mI (751) pwm: --- PWM v3.2
.[0m
[prt] log level set as: [ 4 ].[0;33mW (771) wrapper_kv: nvs get blob ssid failed with 1102.[0m
.[1;31m[crt] awss_config_press(180): enable awss

.[0m.[0;32mI (781) app main: IOTX_AWSS_ENABLE.[0m
.[0;32mI (781) app main: IOTX_AWSS_START.[0m
.[1;33m[inf] zconfig_init(260): zconfig_init

.[0m.[0;32mI (801) awss: Open monitor mode.[0m
.[1;31m[crt] aws_switch_channel(166): chan 1

.[0m.[1;31m[crt] awss_save_apinfo(271): [1] ssid:newifi_5BB8, mac:207693245bb8, chn:1, rssi:-61, adha:0

.[0m.[1;31m[crt] aws_switch_channel(166): chan 6

.[0m.[1;31m[crt] awss_save_apinfo(271): [2] ssid:zheng, mac:c061187f704f, chn:11, rssi:-62, adha:0

.[0m.[1;31m[crt] awss_save_apinfo(271): [3] ssid:TP-LINK_F466, mac:3496727ff466, chn:6, rssi:-76, adha:0

.[0m.[1;31m[crt] aws_switch_channel(166): chan 11

.[0m.[1;31m[crt] awss_save_apinfo(271): [4] ssid:TP-LINK_C9FA, mac:9ca6155ac9fa, chn:11, rssi:-84, adha:0

.[0m.[1;31m[crt] aws_switch_channel(166): chan 1

.[0m.[1;31m[crt] aws_switch_channel(166): chan 2

.[0m.[1;31m[crt] aws_switch_channel(166): chan 3

.[0m.[1;31m[crt] awss_save_apinfo(271): [5] ssid:ChinaNet-yMW4, mac:fc372b8e4d49, chn:3, rssi:-90, adha:0

.[0m.[1;31m[crt] aws_switch_channel(166): chan 4

.[0m.[1;31m[crt] aws_switch_channel(166): chan 5

.[0m.[1;31m[crt] aws_switch_channel(166): chan 6

.[0m.[1;31m[crt] aws_switch_channel(166): chan 7

.[0m.[1;31m[crt] aws_switch_channel(166): chan 8

.[0m.[1;31m[crt] aws_switch_channel(166): chan 9

.[0m.[1;31m[crt] aws_switch_channel(166): chan 10

.[0m.[1;31m[crt] aws_switch_channel(166): chan 11

.[0m.[1;31m[crt] aws_switch_channel(166): chan 12

**Comment by ljy770** [comment]
您好， 设备上电后不断的打印.[0m.[1;31m[crt] aws_switch_channel(166): 这是设备进入了配网状态，是没有问题的。
这里是阿里云的配网方式，您用 IOT_Espressif_EspTouch 是不匹配的，需要用阿里云提供的云智能APP，从上一回复里面提供的链接下载。您可以先试一下用这个 APP 配网。
三元组信息是否已经烧录？ 不然配网会不成功。

**Comment by angle600** [comment]
> 您好， 设备上电后不断的打印.[0m.[1;31m[crt] aws_switch_channel(166): 这是设备进入了配网状态，是没有问题的。
> 这里是阿里云的配网方式，您用 IOT_Espressif_EspTouch 是不匹配的，需要用阿里云提供的云智能APP，从上一回复里面提供的链接下载。您可以先试一下用这个 APP 配网。
> 三元组信息是否已经烧录？ 不然配网会不成功。

---------------------------------------------------------------------------------------------------------------
我烧了https://www.aligenie.com提供的三元组啊，难道不能直连精灵云？
smartconfig还分版本的？传送的SSID与密码是加密的？

**Comment by xuhongv** [comment]
阿里云生活物联网架构师专题 ①】esp32 sdk 直连接入阿里云物联网平台，实现天猫精灵语音控制； - 徐宏的博客。 - CSDN博客 https://blog.csdn.net/xh870189248/article/details/101363357

@angle600
