### ISSUE TITLE
阿里三元组，是三个键值对，但是量产工具说明里，却有四个；多出的那个怎么来的？

### ISSUE THREAD

**Issue by huozhe0930** [espressif/esp-aliyun#146]
阿里三元组：
ProductKey
DeviceName
DeviceSecret
量产工具说明：
DeviceName
DeviceSecret
ProductKey
ProductSecret
比阿里三元组多了一个ProdectSecret。这个ProdectSecret怎么得来的呢？

**Comment by ljy770** [comment]
@huozhe0930 创建产品时和 Product Key 同时产生的. 在产品基本信息中可以找到.

**Comment by huozhe0930** [comment]
谢谢，我没注意；到里面找下。

**Comment by xuhongv** [comment]
@huozhe0930 
esp32 sdk 直连接入阿里云物联网平台，实现天猫精灵语音控制； - 徐宏的博客。 - CSDN博客 https://blog.csdn.net/xh870189248/article/details/101363357

**Comment by xuhongv** [comment]
![image](https://user-images.githubusercontent.com/25237870/66393766-f6ed6580-ea05-11e9-8dc5-b515faf57db1.png)

**Comment by huozhe0930** [comment]
找到了，谢谢各位的回复。
