### ISSUE TITLE
按说明文档操作：make menuconfig阶段，未找到设置ssid和password的选项

### ISSUE THREAD

**Issue by huozhe0930** [espressif/esp-aliyun#148]
配置烧写串口
    配置 WIFI_SSID, WIFI_PASSWORD  <---在菜单中未找到该选项。

**Comment by xuhongv** [comment]
- 文档未更新，可以参考这个:
esp32 sdk 直连接入阿里云物联网平台，实现天猫精灵语音控制； - 徐宏的博客。 - CSDN博客 https://blog.csdn.net/xh870189248/article/details/101363357

**Comment by huozhe0930** [comment]
谢谢，我看看

**Comment by huozhe0930** [comment]
已经实现，谢谢。
