### ISSUE TITLE
ESP8266 阿里IOT平台 一型一密

### ISSUE THREAD

**Issue by IotSHCJC** [espressif/esp-aliyun#149]
我想使用阿里平台的一型一密，
在mqtt_wrapper.h文件中定义了，#define DYNAMIC_REGISTER  1
在IOT_MQTT_Construct函数我修改了以下地方：
int dynamic = 1;
/* Set dynamic option */
IOT_Ioctl(IOTX_IOCTL_SET_DYNAMIC_REGISTER, (void *)&dynamic);
但是没有成功，提示如下：
Invalid device secret, abort!
[0m[0;33mW (3366) wrapper_kv: nvs get blob DYNAMIC_REG_A2rmvkYMKQ98MM59XQEZ failed with 1102[0m
[1;33m[inf] _iotx_dynamic_register(310): DeviceSecret KV not exist, Now We Need Dynamic Register...
[0m[1;33m[inf] _calc_dynreg_sign(127): Random Key: 8Ygb7ULYh53B6OA
[0m[1;33m[inf] _calc_dynreg_sign(143): Sign: 6F6E335AC31DE6A4265ED053C08D2B23879C47BC42E0B8254DD3FA71C0AF48EF
[0m[1;33m[inf] _http_recv(214): ret of _http_recv is 32
[0m[1;33m[inf] _http_recv(214): ret of _http_recv is 32
[0m[1;33m[inf] _http_recv(214): ret of _http_recv is 32
[0m[1;33m[inf] _http_recv(214): ret of _http_recv is 32
[0m[1;33m[inf] _http_recv(214): ret of _http_recv is 32
[0m[1;33m[inf] _http_recv(214): ret of _http_recv is 136
[0m[1;33m[inf] httpclient_common(570): close http channel
[0m[1;33m[inf] httpclient_close(502): client disconnected
[0m[1;33m[inf] _fetch_dynreg_http_resp(200): 
[0m[1;33m[inf] _fetch_dynreg_http_resp(203): Dynamic Register Code: 200
[0m[1;33m[inf] _fetch_dynreg_http_resp(213): Dynamic Register Device Secret: A5MisKY5s5XFg5MXdTJuaIhKnxtt9dDI
[0m[0;31mE (6266) wrapper_kv: nvs erase key DYNAMIC_REG_A2rmvkYMKQ98MM59XQEZ failed with 1109[0m
[1;31m[err] _iotx_dynamic_register(320): Save Device Secret to KV Failed
[0m[1;31m[err] IOT_MQTT_Construct(419): ret = _iotx_dynamic_register() = -1, abort
[0mmqtt_main|227 :: MQTT construct failed

Task stack [mqtt_example] stack from [0x3fff4898] to [0x3fff7094], total [10240] size

                   0          4          8          c         10         14         18         1c         20         24         28         2c         30         34         38         3c 

3fff7058  0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x402449c0 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 

        PC: 0x00000000        PS: 0x00000030        A0: 0x00000000        A1: 0x3fff7090
        A2: 0xffffffff        A3: 0x00000000        A4: 0x00000005        A5: 0x00000000
        A6: 0x40250764        A7: 0x000001f4        A8: 0x00000000        A9: 0x00000310
       A10: 0x3fff6ec4       A11: 0x401066e8       A12: 0x00000000       A13: 0x00000000
       A14: 0x00000000       A15: 0x00000000       SAR: 0x00000004  EXCCAUSE: 0x00000014

Task stack [mqtt_example] stack from [0x3fff4898] to [0x3fff7094], total [10240] size

**Comment by simonliu009** [comment]
我觉得你应该先擦除flash再烧录试试
