### ISSUE TITLE
如何获取OTA固件版本信息？

### ISSUE THREAD

**Issue by bestkeen** [espressif/esp-aliyun#150]
在OTA demo 中，关于”上传固件版本号需要和当前版本号不同. 上传固件版本名称与实际固件版本保持一致“。如何获取实际固件版本信息？在alios中，编译固件时，编译信息中有固件版本，但是在esp-aliyun 中却没有本信息？在Smartlight demo中，自定义固件号，可以进行升级，并且升级成功，但是，在阿里云平台中，验证固件失败。
Bestregards,
keen

**Comment by ljy770** [comment]
"上传固件版本名称与实际固件版本保持一致“ 即编译待升级固件时设置版本号, make menuconfig->Component config ->iotkit embedded -> aliyun linkkit device version -> Device version.
等升级成功之后,会上报这个版本号,云端会和您填写在云端的固件版本号对比,一致则判断升级成功.

**Comment by bestkeen** [comment]
Thank you so much, it works! Answer so quickly, Give you a like!
Bestregards,
keen

**Comment by szd117** [comment]
能说一下OTA的流程吗
