### ISSUE TITLE
目前的版本支持设备热点配网吗？

### ISSUE THREAD

**Issue by hqchen118** [espressif/esp-aliyun#151]
## 2. 问题描述

int HAL_Awss_Open_Ap(const char *ssid, const char *passwd, int beacon_interval, int hide)
{
    return (int)1;
}

int HAL_Awss_Close_Ap(void)
{
    return (int)1;
}

这两个函数没有实现

**Comment by ljy770** [comment]
您好,目前没有支持设备热点配网.
