### ISSUE TITLE
esp8266 设备解绑失败

### ISSUE THREAD

**Issue by bestkeen** [espressif/esp-aliyun#152]
你好，我这边使用solution demo测试设备解绑时，在使用手机端公版“云智能”app,解绑设备时，esp 8266 提示“iotx_mc_deliver_message(1280): NO matching any topic, call default handle function” ，请问有没有什么好的方法解决这个问题？
Bestregards,
keen

**Comment by ljy770** [comment]
您好,这里到不能说是解绑失败,按照阿里云官方说法,绑定主要还是说的手机的受信任过程. 解除绑定,就是解除了手机端对设备的操控. 至于设备还是会正常运行,手机端无法再控制设备.
打印上述 log, 原因是并没有注册相关的 topic, 如果打印 payload 信息,发现是通知设备解绑操作:
```
[inf] iotx_mc_deliver_message(1280): NO matching any topic, call default handle function
[wrn] iotx_cloud_conn_mqtt_event_handle(178): bypass 141 bytes on [/sys/a1JD3X3ZyFx/light_03/_thing/event/notify]
[wrn] iotx_cloud_conn_mqtt_event_handle(179): {"method":"_thing.event.notify","id":"1880440452","params":{"identifier":"awss.BindNotify","value":{"Operation":"Unbind"}},"version":"1.0.0"}
```

**Comment by bestkeen** [comment]
因为我这边需要在收到解绑信息后，进行设备wifi信息擦除，和设备重启。那么如何注册相关的topic?
Bestregards,
keen

**Comment by ljy770** [comment]
dm_client_subscribe_all 函数中, 通过 g_dm_client_uri_map 注册 Topic, 您需要在g_dm_client_uri_map中添加相应的 Topic 和处理 handle. 可以参照其他 handle 的实现,最后可以把事件 post 到 应用中(linkkit_solo.c),来做设备wifi信息擦除，和设备重启.

**Comment by Eavo** [comment]
@bestkeen 您好，这个功能我们还未经过验证，您可以参照以上的方法去尝试实现。如果您需要定制需求的话，可以联系我们的商务：sales@espressif.com。谢谢。

**Comment by bestkeen** [comment]
@Eavo 好的，收到，我这边测试一下，非常感谢您的技术支持！
