### ISSUE TITLE
这个esp-aliyun是否同时支持一键配网和蓝牙配网

### ISSUE THREAD

**Issue by hscxg** [espressif/esp-aliyun#162]
我们现在准备采用ESP32开发一款连接阿里飞燕的一款产品, 请问一下, 这个开发包是否同时支持一键配网和蓝牙配网? 另外热点配网也支持吗?

**Comment by Eavo** [comment]
我们默认是一键配网和零配。

**Comment by hscxg** [comment]
由于考虑到一键配网可能会失败问题,  我们这个产品特地选用了ESP32芯片, 就是想实现蓝牙配网, 以蓝牙配网为主, 以一键配网为辅, 并要求在任何时候都可以进行蓝牙配网.
请问一下, 这种方案好实现吗? WIFI和蓝牙共存会有冲突吗?

**Comment by ljy770** [comment]
您好, 好实现, 蓝牙只是配网和WIFI冲突问题不大.

**Comment by hscxg** [comment]
目前ESP32连接阿里飞燕后台的项目smart_light和ESP32蓝牙配网项目BluFi, 我单独测试都已经通过, 但是如何将BluFi整合到smart_light项目中来, 我还是一头雾水, 不知如何下手, 有没有指导文档啊? 请求帮助, 谢谢!

**Comment by ljy770** [comment]
主要是要解决蓝牙配网成功后如何通知阿里云侧

**Comment by Eavo** [comment]
为了方便管理，我们将关闭该问题。如果还有遗留问题，欢迎随时 reopen issue，谢谢。
