### ISSUE TITLE
阿里推出了3.1版本的SDK，支持了我的项目非常想用的一些特性；什么时候能移植过来？

### ISSUE THREAD

**Issue by huozhe0930** [espressif/esp-aliyun#163]
如果还没有具体的移植计划，自己移植可行吗？
能否给一些有益的指导？

**Comment by ljy770** [comment]
您好,暂时没有移植 3.1 的计划, 您可以参考 esp-aliyun release/v2.0 版本的移植方式, 将 3.1 版本的 aliyun/iotkit-embedded source code 移到 esp-aliyun/iotkit-embedded 中, 需要实现的接口在 esp-aliyun/wrappers 文件夹下实现.

**Comment by huozhe0930** [comment]
谢谢。
