### ISSUE TITLE
esp_aliyun增加蓝牙配网功能求助

### ISSUE THREAD

**Issue by hscxg** [espressif/esp-aliyun#166]
esp-aliyun中的smart_light这个项目我这边已经调试通过, 可以连接上阿里云, 并且读写阿里云后台数据, 遗憾的是, 这个项目没有蓝牙配网功能,  但我们的产品要求带有蓝牙配网功能, 所以我就仿照BluFi例程项目代码, 我将蓝牙初始化代码移植到smart_light这个项目上来, 程序编译也通过了, 烧录到ESP32开发板后, 运行程序, 程序却在不断反复重启, LOG有报告错误信息:
E (645) esp_image: Image length 1350192 doesn't fit in partition length 1048576
E (645) boot: OTA app partition slot 0 is not bootable
E (648) esp_image: image at 0x110000 has invalid magic byte
W (654) esp_image: image at 0x110000 has invalid SPI mode 162
E (660) boot: OTA app partition slot 1 is not bootable
E (666) boot: No bootable app partitions in the partition table
看起来好像是ESP32分区表设置有误, 这种情况下, 不知如何配置分区表, 请指点, 谢谢!

![P1](https://user-images.githubusercontent.com/55936147/69129493-6cf6e900-0ae9-11ea-9842-afe62d912c8c.jpg)

**Comment by xuhongv** [comment]
- 固件太大了，和你定义的分区有冲突；
- 解决方法，重新自定义分区表吧

**Comment by Eavo** [comment]
为了方便管理，我们将关闭该问题。如果还有遗留问题，欢迎随时 reopen issue，谢谢。
