### ISSUE TITLE
这个esp-aliyun支持连接阿里云的国际站吗

### ISSUE THREAD

**Issue by hscxg** [espressif/esp-aliyun#168]
经测试, 这个esp-aliyun连接阿里云的中国站没有问题,  由于我们的产品是需要连接阿里云的国际站, 但我试着连接国际站时, 没有成功.

请问一下,  这个esp-aliyun支持连接阿里云的国际站吗, 如果支持的话, 是否需要一些其它配置?

谢谢!

**Comment by ljy770** [comment]
您好, 还没有试过连接国际站, 应该是支持的,可能需要一些特殊的配置. 
(1) 按照阿里云文档:https://g.alicdn.com/aic/ilop-docs/2018.10.35/international.html
需要在国际站创建产品.
(2) esp-aliyun/examples/solutions/smart_light/components/linkkit_handle/linkkit_solo.c :
domain_type = IOTX_CLOUD_REGION_SHANGHAI;
这里改一下地区.
试试看呢.

**Comment by wanglemao** [comment]
@ljy770 里面还有一个关于 MQTT 直连和预认证的切换，但是我在esp-aliyun没有找到这个选项，但是官网说这个会导致设备无法上线，请问这个有影响的么？

**Comment by ljy770** [comment]
阿里云选项的位置在 iotkit-embedded\infra\infra_config.h, MQTT 直连默认是支持的.

**Comment by wanglemao** [comment]
我尝试了，连接美国是不行的，我咨询了阿里的技术支持，说要采用他们生活平台的sdk，否则出问题不管。。。

**Comment by ljy770** [comment]
设备是否是在 美国地区连接的美国服务器呢? 
如果需要我们进一步解决这个问题, 可以联系商务 sales@espressif.com

**Comment by ljy770** [comment]
@wanglemao @hscxg 

国家版的功能已经添加,使用 https://github.com/espressif/esp-aliyun master 版本更新到最新, 操作说明在  esp-aliyun/examples/solutions/smart_light/README.md (14.国际站设备开发)
