### ISSUE TITLE
执行 ./gen_misc.sh 出错

### ISSUE THREAD

**Issue by wangqinx** [espressif/esp-aliyun#17]
如题，执行的时候会直接把gen_misc.sh里的文本内容打印出来，而不是开始生成固件文件的流程。在官方镜像和cygwin下都是一样的现象。请问如何解决？

**Comment by liefyuan** [comment]
哥们，我现在也是遇到这个问题呢

**Comment by liefyuan** [comment]
好巧啊

**Comment by liefyuan** [comment]
我刚刚也提交了一个issue呢

**Comment by wangqinx** [comment]
呵呵，真巧。说来惭愧刚提交问题就找到解决办法了：

从乐鑫官网下载基于RTOS的SDK，然后解压到阿里云SDK的/esp8266-rtos-sdk 目录下即可顺利生成固件镜像。

**Comment by liefyuan** [comment]
nice!!
