### ISSUE TITLE
现在的版本是否已经实现设备影子部分的代码？

### ISSUE THREAD

**Issue by simonliu009** [espressif/esp-aliyun#179]
我看了下menuconfig中没有找到对应的选项。
也没有在源码中搜到原厂c-sdk提供的设备影子API。

**Comment by ljy770** [comment]
在 esp-aliyun/iotkit-embedded/infra/infra_config.h
中有默认设置
#define DEVICE_MODEL_SHADOW

**Comment by simonliu009** [comment]
好的 谢谢 我再去看看

**Comment by Eavo** [comment]
为了方便管理，我们将关闭该问题。如果还有遗留问题，欢迎随时 reopen issue，谢谢。
