### ISSUE TITLE
如何使用COTA（远程配置）功能

### ISSUE THREAD

**Issue by szd117** [espressif/esp-aliyun#182]
使用的是smartlight例程，现在想测试下COTA功能。
是进行如下定义吗？
#define FEATURE_SERVICE_OTA_ENABLED y

**Comment by ljy770** [comment]
默认已经开启了 OTA 功能，你可以查看 examples\solutions\smart_light\README.md 中关于 OTA　的说明。不知道您说的　COTA　和　这里的　OTA　是不是一样的？还是这是新的OTA功能？
