### ISSUE TITLE
执行./gen_misc.sh 时无法选择配置

### ISSUE THREAD

**Issue by wangqinx** [espressif/esp-aliyun#19]
如题，执行./gen_misc.sh ，系统会直接打印出gen_misc.sh中的文本内容并开始编译。

问题是我这边的FLASH是DOUT模式的，如果不能选择编译模式的话生成的固件在我的模块上就没法工作，请大手子指教。

**Comment by ustccw** [comment]
@wangqinx gen_misc.sh 是通用的，将你的脚本复制过来即可。注意需要重新导入环境变量 `SDK_PATH` 和 `BIN_PATH`

**Comment by wangqinx** [comment]
@ustccw 解决了，我在linux下直接修改.sh文件的缺省值，可以正常编译。
