### ISSUE TITLE
MQTT 连接不稳定当前状态

### ISSUE THREAD

**Issue by wanfangbing** [espressif/esp-aliyun#23]
前面3月初有其他开发者提到的MQTT 连接不稳定问题现在状态是怎样的？
之前MQTT 连接不稳定的问题最新的状态是怎样的

**Comment by ustccw** [comment]
@wanfangbing 您好，当前MQTT 连接不稳定确实存在，我们会在接下来2周着手修复，感谢您的关注。

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
