### ISSUE TITLE
想要适配最新版的阿里云SDK，如何适配？

### ISSUE THREAD

**Issue by wuchuhua** [espressif/esp-aliyun#27]
我们的项目用到了阿里云设备认证中的一型一密认证方式，需要移植最新版V2.10的阿里云SDK，请问如何适配？

**Comment by wangqinx** [comment]
同问这个问题。另外，阿里云一型一密的入口

FEATURE_SUPPORT_PRODUCT_SECRET = y

这一句在哪个文件里？

**Comment by ustccw** [comment]
@wuchuhua @wangqinx 当前已更新至 v2.10
一型一密 demo 暂未提供，可参考 mqtt-demo。

**Comment by sofwu** [comment]
@ustccw 型一密 demo什么时候可以做出来

**Comment by ustccw** [comment]
@sofwu 你好，目前有计划，但无法确定具体的工作安排

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
