### ISSUE TITLE
设备影子创建错误

### ISSUE THREAD

**Issue by lanseyujie** [espressif/esp-aliyun#28]
调用 IOT_Shadow_Construct 时会因 HAL_MutexCreate 返回 NULL 报错 create mutex failed。
文件路径：./esp8266-aliyun/platforms/aliyun/IoT-SDK_V2.0/src/shadow/shadow.c
![_ _20180513114141](https://user-images.githubusercontent.com/16262938/39963602-f2b86b2e-56a2-11e8-847d-15ddc92de047.png)

**Comment by ustccw** [comment]
@lanseyujie 当前已更新至 v2.10, 请重新试下看看

**Comment by lanseyujie** [comment]
@ustccw 测试OK, Thank you.
