### ISSUE TITLE
串口输出乱码问题

### ISSUE THREAD

**Issue by BlueSkyai** [espressif/esp-aliyun#3]
你好，可以用sercureCRT测一下显示吗？

**Comment by BlueSkyai** [comment]
此外，我如果要用串口0，程序怎么修改能用串口1输出呢？

**Comment by ustccw** [comment]
@BlueSkyai secureCRT没问题的。
![secureali](https://user-images.githubusercontent.com/24221485/34284472-3a39a270-e70d-11e7-937c-60027826d3a8.jpg)

**Comment by BlueSkyai** [comment]
@ustccw 为什么我的是乱码，是secureCRT哪里设置的不对吗？

**Comment by ustccw** [comment]
@BlueSkyai 建议你先根据官方文档，跑出一个hello world.

**Comment by BlueSkyai** [comment]
@ustccw 可以了，谢谢
![2](https://user-images.githubusercontent.com/31559830/34298218-9832319a-e757-11e7-96dd-2ee69a2a6ea8.png)

**Comment by ustccw** [comment]
感谢你对esp的关注
