### ISSUE TITLE
最新版本的编译失败

### ISSUE THREAD

**Issue by sofwu** [espressif/esp-aliyun#30]
$ ./gen_misc.sh
./gen_misc.sh:行2: $'\r': 未找到命令
./gen_misc.sh:行10: $'\r': 未找到命令
./gen_misc.sh:行13: $'\r': 未找到命令
/home/esp8266-aliyun-demo/esp8266-rtos-sdk
/home/esp8266-aliyun-demo/bin
./gen_misc.sh:行16: $'\r': 未找到命令
gen_misc.sh version 20150911

./gen_misc.sh:行19: $'\r': 未找到命令
./gen_misc.sh:行99: 语法错误: 未预期的文件结尾

**Comment by seblee** [comment]
环境没配置好吧

**Comment by ustccw** [comment]
@sofwu 确认下您的编译器可否编译其他 ESP8266 下例子

**Comment by sofwu** [comment]
@ustccw 之前的版本是可以的！！
