### ISSUE TITLE
OTA升级历程没了吗？老版本都有可以用的OTA历程

### ISSUE THREAD

**Issue by Yvan623048750** [espressif/esp-aliyun#33]
OTA升级历程没了吗？老版本都有可以用的OTA历程；

什么时候会加上OTA的支持历程呢？

**Comment by ustccw** [comment]
@Yvan623048750 后期会加上的，时间待定。

**Comment by Yvan623048750** [comment]
有个大概的时间吗？一个月？因为最近我们公司正用ESP8266使用阿里云平台研发产品

**Comment by ustccw** [comment]
@Yvan623048750 一个月可以

**Comment by Yvan623048750** [comment]
非常感谢！研发过程发现什么问题也会第一时间反馈给你们

**Comment by ustccw** [comment]
好

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
