### ISSUE TITLE
工程编译太慢了，去掉脚本的make clean 也还是很慢，比旧版本慢很多很多，调试非常麻烦

### ISSUE THREAD

**Issue by Yvan623048750** [espressif/esp-aliyun#34]

**Comment by ustccw** [comment]
@Yvan623048750 请问，是编译哪部分慢呢，现在加入了编译阿里 SDK, 您可以注释 `gen_misc.sh` 中
```
# make aliyun
# make clean
```

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
