### ISSUE TITLE
新的程序怎么没有IoT-SDK_V2.0目录了？

### ISSUE THREAD

**Issue by mygreatnet** [espressif/esp-aliyun#36]
如题

**Comment by ustccw** [comment]
@mygreatnet 最新的 mater 已更新阿里 SDK，从 v2.0 更新至 v2.10.
现在的 `components/aliyun/iotkit-embedded` 即为以前的 `IoT-SDK_V2.0` 新版本

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
