### ISSUE TITLE
使用串口1 打印问题

### ISSUE THREAD

**Issue by BlueSkyai** [espressif/esp-aliyun#4]
@ustccw 你好，之前切换串口都是取消uart.c中的一句 os_install_putc1注释，现在这样的办法在库程序中还有效吗？串口我需要和其他cpu通信，初看了一下程序通过串口打印信息的方式有很多，不知道有没有关联

**Comment by BlueSkyai** [comment]
@ustccw 你好，我从uart.c中串口设置函数uart_setprintport( )修改了uart1为默认输出，但是仍是从uart0输出打印信息，请问，在此库函数中应当如何修改设置？我的理解就这么多了

**Comment by BlueSkyai** [comment]
@ustccw 你好，请问库程序切换到串口1输出有没有什么办法？

**Comment by BlueSkyai** [comment]
@igrr

**Comment by ustccw** [comment]
@BlueSkyai 你好，先调用 system_uart_swap() 再调用 UART_SetPrintPort() 可切换串口，请知悉。

**Comment by BlueSkyai** [comment]
@ustccw 编译没通过，undefined reference to `UART_SetPrintPort'，不知为什么
![qq 20171227152205](https://user-images.githubusercontent.com/31559830/34374059-dfa07972-eb19-11e7-9ab5-d651f44d0ab1.png)

**Comment by BlueSkyai** [comment]
@ustccw 你好，Linux环境也是同样问题
![qq](https://user-images.githubusercontent.com/31559830/34374935-c719c8ae-eb1e-11e7-82bc-401f72ef0270.png)

**Comment by ustccw** [comment]
@BlueSkyai 你好，需要链接 libdriver.a , 请修改 esp8266-aliyun/Makefile。 如下:
![_001](https://user-images.githubusercontent.com/24221485/34375489-bf474e96-eb21-11e7-8822-d2f35eab649a.png)

**Comment by BlueSkyai** [comment]
@ustccw 串口0有一些输出，不知道是不是8266通常上电打印的信息，然后串口1的输出就很少了，我显示的乱码，没有和默认输出一样，定时输出mqtt的消息
![20171227165201](https://user-images.githubusercontent.com/31559830/34376465-ccae3a90-eb26-11e7-8e46-23407c9a0e36.png)
![2017122716531](https://user-images.githubusercontent.com/31559830/34376470-d461ab50-eb26-11e7-8324-2f8304043a13.png)

**Comment by ustccw** [comment]
@BlueSkyai Hi, dear，上面说法有误，下面方法亲测有效:
![_002](https://user-images.githubusercontent.com/24221485/34380666-3b70e218-eb3e-11e7-90ca-aeadaed9c98b.png)

**Comment by BlueSkyai** [comment]
@ustccw thankyou very much！

**Comment by ustccw** [comment]
my honor
