### ISSUE TITLE
在ubantu下编译出来的SDK串口一直输出乱码

### ISSUE THREAD

**Issue by titawork** [espressif/esp-aliyun#41]
按照教程在ubantu 16.04 下编译出来SDK，一直输出乱码。
尝试过：
1. 使用默认 74880 ，还是乱码
2. 增加函数设置波特率为 115200， 还是乱码
3. 增加定时器，间隔2s控制灯闪，运行后灯会闪，说明程序已经在运行，就是无法用secureCRT接收到正常的日志。
4. 使用之前自己编译的SDK，能正常输出日志。

有没有遇到这种情况的？

**Comment by titawork** [comment]
天坑，在ubantu上用 miniterm.py 就可以。

**Comment by ustccw** [comment]
@titawork 你好，默认波特率是 74880,乱码是否是由于串口工具配置造成的。

**Comment by titawork** [comment]
乱码不是工具配置造成的，因为烧其他程序进去是好的，就是阿里云的SDK不行。但是使用miniterm.py 是不乱码的就先不追究了，这个问题先关掉
