### ISSUE TITLE
HSPI 驱动接口怎么配置？一配置就不断中断回调死机

### ISSUE THREAD

**Issue by Yvan623048750** [espressif/esp-aliyun#45]
SpiAttr hspi;
			
	hspi.mode		= SpiMode_Slave;
	hspi.speed		= SpiSpeed_10MHz;
	hspi.subMode	= SpiSubMode_1;
	hspi.bitOrder	= SpiBitOrder_LSBFirst;
	
	
	SPIInit(SpiNum_HSPI,&hspi);
	SPISlaveRecvData(SpiNum_HSPI,hspi_rece_callback);

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
