### ISSUE TITLE
连接十分不稳定，并且会导致异常重启

### ISSUE THREAD

**Issue by alvminvm** [espressif/esp-aliyun#49]
mqtt连接上之后，会经常出现断开。
在回调`event_handle`中经常打印`MQTT disconnect.`和 `MQTT reconnect.`

并且有一定概率在出现 `MQTT disconnect.`时，模组异常重启。
严重影响模组的正常业务功能！！！
完全无法投入使用。

不稳定这个问题我看从很早就有人提出了，但是一直没解决。希望重视这个问题！！

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
