### ISSUE TITLE
xTaskCreate 调度问题

### ISSUE THREAD

**Issue by BlueSkyai** [espressif/esp-aliyun#5]
@ustccw 你好，库程序里的usermain.c里的xTaskCreate(mqtt_proc，...)，我没有发现调度器vTaskStartScheduler()的身影，然后任务mqtt_proc就启动了，我想问在库程序里只要创建一个任务就默认开始运行了吗？
此外，tls连接是只要用库程序进行MQTT通讯就默认开始内置连接吗？

**Comment by ustccw** [comment]
@BlueSkyai xTaskCreate 之后，会根据 task 优先级自动调度, 无需使用 vTaskStartScheduler()

不同的问题请用不同的 issue,谢谢！

**Comment by BlueSkyai** [comment]
@ustccw 如果是外部中断响应的任务，需要通知任务执行吗，或者是有些类似查询，任务按照优先级循环执行？在sdk之前的版本我是通过system_os_task和system_os_post来创建和执行任务的。

**Comment by ustccw** [comment]
@BlueSkyai system_os_task(创建系统任务) 和 system_os_post(向任务发送消息) 是 ESP8266_NONOS_SDK 中的接口。
其余的参考 FreeRTOS 内核。
