### ISSUE TITLE
子模块iotkit-embedded里的东西没法clone下来

### ISSUE THREAD

**Issue by shangzhe** [espressif/esp-aliyun#55]
如题   
子模块iotkit-embedded里的东西没法clone下来

**Comment by ustccw** [comment]
@shangzhe 试试这个？[加快github下载代码的速度](https://blog.csdn.net/mist99/article/details/80602090)

**Comment by ghost** [comment]
不是代码速度的问题,挂代理也不行的,看log找地址,自己到阿里云的github上克隆吧,不过,我克隆下来的编译不通过...

**Comment by ustccw** [comment]
这个由于阿里删除 v2.10 分支，导致这边 submodule clone 不了。目前已将 SDK 以源码形式提供
