### ISSUE TITLE
esp8266-aliyun-demo是不是删掉了，是要放新版本吗

### ISSUE THREAD

**Issue by SunJun8** [espressif/esp-aliyun#57]

**Comment by shangzhe** [comment]
在线等 答案

**Comment by 27-301** [comment]
改名了，当前 esp-aliyun 支持 ESP-IDF & ESP8266_RTOS_SDK v3.0。如果需要使用基于 ESP8266_RTOS_SDK v2.x.x 的版本，checkout feature/for_esp8266_rtos_sdk_v2.x.x 。

如果想基于 RTOS 3.0，请看一下最新的 readme。

**Comment by SunJun8** [comment]
@27-301 在ESP-IDF中运行make clean，默认toolchain就变成lx106,只能重新git clone

**Comment by 27-301** [comment]
你用的 8266 RTOS SDK 还是 32 IDF？IDF_PATH 指向哪？

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
