### ISSUE TITLE
您好，在make menuconfig时出错了。

### ISSUE THREAD

**Issue by SunJun8** [espressif/esp-aliyun#58]
按照实例对example下mqtt进行操作，出现如下错误：

Makefile:16: /home/jojo/esp/esp-aliyun/examples/mqtt/../../esp-idf/make/project.mk: 没有那个文件或目录
make: *** No rule to make target '/home/jojo/esp/esp-aliyun/examples/mqtt/../../esp-idf/make/project.mk'。 停止。

查看makefile，16 line:include $(IDF_PATH)/make/project.mk
尝试修改IDF_PATH为绝对路径，还是不行，可能在其他位置依旧无法识别IDF_PATH,但是环境变量的确已经配置好了，不知道是哪的问题。

**Comment by 27-301** [comment]
你的 IDF_PATH 设置到哪了？

你可以在 shell 里 export IDF_PATH=~/esp/ESP8266_RTOS_SDK 这样

**Comment by SunJun8** [comment]
@27-301 非常感谢！！
按照新流程整个重新配置了8266的环境，已经可以工作。
请问mqtt_example.c中使用的函数分别在哪些文件中声明？很多函数只看到调用。谢谢！

**Comment by ustccw** [comment]
@24540477zxc 可以参考下面宏：
```
COMPONENT_ADD_INCLUDEDIRS := \
    iotkit-embedded/src/sdk-impl \
    iotkit-embedded/src/sdk-impl/exports \
    iotkit-embedded/src/sdk-impl/imports \
    iotkit-embedded/src/packages/LITE-utils \
    iotkit-embedded/src/log/LITE-log
```
