### ISSUE TITLE
mqtt还是会断开 很不稳定

### ISSUE THREAD

**Issue by shangzhe** [espressif/esp-aliyun#59]
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
[inf] iotx_mc_keepalive_sub(2226): send MQTT ping...
[inf] iotx_mc_cycle(1295): receive ping response!
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
[inf] iotx_mc_keepalive_sub(2226): send MQTT ping...
[inf] iotx_mc_cycle(1295): receive ping response!
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
[inf] _network_ssl_read(456): ssl recv error: code = -30848, err_str = ''
[dbg] iotx_mc_read_packet(744): mqtt read error, rc=-2
[dbg] iotx_mc_cycle(1239): readPacket error,result = -1
[err] iotx_mc_keepalive(1871): network is disconnected!
event_handle|086 :: MQTT disconnect.
[inf] _network_ssl_disconnect(519): ssl_disconnect
[dbg] iotx_mc_cycle(1225): state = 4
[inf] IOT_MQTT_Yield(2415): error occur 
[inf] iotx_mc_handle_reconnect(2072): Waiting to reconnect...
[inf] iotx_mc_handle_reconnect(2078): start to reconnect
[dbg] guider_print_dev_guider_info(256): ....................................................
[dbg] guider_print_dev_guider_info(257):           ProductKey : iXTESaYy3TG
[dbg] guider_print_dev_guider_info(258):           DeviceName : 60019473763A
[dbg] guider_print_dev_guider_info(259):             DeviceID : iXTESaYy3TG.60019473763A
[dbg] guider_print_dev_guider_info(261): ....................................................
[dbg] guider_print_dev_guider_info(262):        PartnerID Buf : ,partner_id=espressif
[dbg] guider_print_dev_guider_info(263):         ModuleID Buf : ,module_id=wroom-32
[dbg] guider_print_dev_guider_info(264):           Guider URL : 
[dbg] guider_print_dev_guider_info(266):       Guider SecMode : 2 (TLS + Direct)
[dbg] guider_print_dev_guider_info(268):     Guider Timestamp : 2524608000000
[dbg] guider_print_dev_guider_info(269): ....................................................
[dbg] guider_print_dev_guider_info(275): ....................................................
[dbg] guider_print_conn_info(233): -----------------------------------------
[dbg] guider_print_conn_info(234):             Host : iXTESaYy3TG.iot-as-mqtt.cn-shanghai.aliyuncs.com
[dbg] guider_print_conn_info(235):             Port : 1883
[dbg] guider_print_conn_info(238):         ClientID : iXTESaYy3TG.60019473763A|securemode=2,timestamp=2524608000000,signmethod=hmacsha1,gw=0,ext=0,partner_id=espressif,module_id=wroom-32|
[dbg] guider_print_conn_info(240):       TLS PubKey : 0x40229d54 ('-----BEGIN CERTI ...')
[dbg] guider_print_conn_info(243): -----------------------------------------
[inf] iotx_mc_attempt_reconnect(2049): reconnect params: MQTTVersion=4, clientID=iXTESaYy3TG.60019473763A|securemode=2,timestamp=2524608000000,signmethod=hmacsha1,gw=0,ext=0,partner_id=espressif,module_id=wroom-32|, keepAliveInterval=60, username=60019473763A&iXTESaYy3TG
[inf] _ssl_client_init(175): Loading the CA root certificate ...
[inf] _ssl_parse_crt(142): crt content:2
[inf] _ssl_client_init(183):  ok (0 skipped)
[inf] _TLSConnectNetwork(345): Connecting to /iXTESaYy3TG.iot-as-mqtt.cn-shanghai.aliyuncs.com/1883...
[inf] _TLSConnectNetwork(358):  ok
[inf] _TLSConnectNetwork(363):   . Setting up the SSL/TLS structure...
[inf] _TLSConnectNetwork(373):  ok
[inf] _TLSConnectNetwork(410): Performing the SSL/TLS handshake...
[inf] _TLSConnectNetwork(418):  ok
[inf] _TLSConnectNetwork(422):   . Verifying peer X.509 certificate..
[inf] _real_confirm(81): certificate verification result: 0x00
[inf] iotx_mc_connect(2035): mqtt connect success!
[inf] iotx_mc_keepalive(1861): network is reconnected!
event_handle|090 :: MQTT reconnect.
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
[inf] iotx_mc_keepalive_sub(2226): send MQTT ping...
[inf] iotx_mc_cycle(1295): receive ping response!
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...
Waiting RRPC from Cloud ...

**Comment by ustccw** [comment]
问题正在排查中

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
