### ISSUE TITLE
HAL_Malloc的malloc可以替换为heap_caps_malloc吗？

### ISSUE THREAD

**Issue by Shaco-Ma** [espressif/esp-aliyun#60]
heap_caps_malloc is use off-chip memory,malloc is use chip memory
I can use heap_caps_malloc instead malloc?

**Comment by 27-301** [comment]
Yes, but it's only available for esp-idf, and esp32-wrover module.

**Comment by Shaco-Ma** [comment]
@27-301 Thanks, I just use it for chip of esp32.
