### ISSUE TITLE
make时出错

### ISSUE THREAD

**Issue by wanghui0574xs** [espressif/esp-aliyun#63]
make: *** No rule to make target `/Users/wanghui/Workspace/GitProject/ESP8266/new/esp-aliyun/examples/mqtt/build/mqtt/component_project_vars.mk', needed by `/Users/wanghui/Workspace/GitProject/ESP8266/new/esp-aliyun/examples/mqtt/build/main.elf'.  Stop.

**Comment by ustccw** [comment]
请根据 README.md 来编译

**Comment by SunJun8** [comment]
@ustccw 请问2.x.x分支会有什么影响吗

**Comment by ustccw** [comment]
@24540477zxc 对 2.x.x 没有影响。请基于 https://github.com/espressif/esp-aliyun/tree/feature/for_esp8266_rtos_sdk_v2.x.x 分支开发。
