### ISSUE TITLE
新的sdk没有这个函数      uart1_write_char  怎么改调试输出呀

### ISSUE THREAD

**Issue by shangzhe** [espressif/esp-aliyun#64]
/**   * @brief     Register the print output function.   *   * @attention os_install_putc1((void *)uart1_write_char) in uart_init will set   *            printf to print from UART 1, otherwise, printf will start from   *            UART 0 by default.   *   * @param     void(*p)(char c) - pointer of print function   *   * @return    null   */ void os_install_putc1(void (*p)(char c));

**Comment by wanghui0574xs** [comment]
在 esp8266_rtos_sdk最新代码里已经实现了.

**Comment by ustccw** [comment]
thanks
