### ISSUE TITLE
HAL_Random

### ISSUE THREAD

**Issue by Shaco-Ma** [espressif/esp-aliyun#67]
I think This function HAL_Random should have some change,because When I use IOT_CMP_INIT to get devicesecret ,This function return some like �B_!��M�=��� , but aliyun need some like 4U29QGvD1lL3Q4.
Maybe like aliyun this function do , return (region > 0) ? (esp_random() % region) : 0,The random num must rand(small rand(26) + 'A' ,small rand(26) + 'a', small '0' + rand(10)), When I open FEATURE_SUPPORT_PRODUCT_SECRET = y, Thanks.

**Comment by ustccw** [comment]
@Shaco-Ma thanks for your advice, will do.
