### ISSUE TITLE
mac下编译make aliyun错误

### ISSUE THREAD

**Issue by wanghui0574xs** [espressif/esp-aliyun#68]
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: /Users/wanghui/Workspace/esp/esp-aliyun/components/aliyun/iotkit-embedded/.O/usr/lib/libiot_sdk.a the table of contents is empty (no object file members in the library define global symbols)

**Comment by ustccw** [comment]
同 https://github.com/espressif/esp-aliyun/issues/72

**Comment by Eavo** [comment]
mac 下编译错误，请参考 #72 修改，之后会更新到 readme 中。
