### ISSUE TITLE
local_ota.c:384:24: error: storage size of 'remote_ip' isn't known

### ISSUE THREAD

**Issue by semieie** [espressif/esp-aliyun#76]
esp8266sdk v2.x.x   aliyun-sdk v2.0.0
在编译refactor时出现了以下错误
local_ota.c:384:24: error: storage size of 'remote_ip' isn't known，
完了我添加了头文件 #include <netinet/in.h> ，又有以下错误
netinet/in.h: No such file or directory

这个工程好难搞，不是这里有问题就是那里有问题。。。

**Comment by semieie** [comment]
我在local_ota.h以及remote_ota.h中添加了
#include "lwip/lwip/sockets.h"
消灭了 local_ota.c:384:24: error: storage size of 'remote_ip' isn't known， 这个错误；
然后出现了新的问题
xtensa-lx106-elf-ar ru .output/eagle/debug/lib/libaliyun_mqtt.a .output/eagle/debug/obj/mqtt.o
xtensa-lx106-elf-ar: creating .output/eagle/debug/lib/libaliyun_mqtt.a
make[1]: Leaving directory '/home/semi/Documents/esp/esp-aliyun-refactor-v2.x.2.10/mqtt'
make: *** No rule to make target 'platforms/.output/eagle/debug/lib/libplatforms.a', needed by '.output/eagle/debug/image/eagle.app.v6.out'.  Stop.

...

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
