### ISSUE TITLE
ESP8266 mqtt连接错误

### ISSUE THREAD

**Issue by donny681** [espressif/esp-aliyun#78]
您好，我使用ESP8266_RTOS_SDK V3.0编译该工程，发现无法连接阿里云后台。我确定product_key和product_secret肯定是正确的，但是一直返回以下错误。

`[inf] _ssl_client_init(175): Loading the CA root certificate ...

[inf] _ssl_parse_crt(142): crt content:2

[inf] _ssl_client_init(183):  ok (0 skipped)

[inf] _TLSConnectNetwork(345): Connecting to /b17UAUgolD6.iot-as-mqtt.cn-
shanghai.aliyuncs.com/1883...

[inf] _TLSConnectNetwork(358):  ok

[inf] _TLSConnectNetwork(363):   . Setting up the SSL/TLS structure...

[inf] _TLSConnectNetwork(373):  ok

[inf] _TLSConnectNetwork(410): Performing the SSL/TLS handshake...

[inf] _TLSConnectNetwork(418):  ok

[inf] _TLSConnectNetwork(422):   . Verifying peer X.509 certificate..

[inf] _real_confirm(81): certificate verification result: 0x00

[err] iotx_mc_wait_CONNACK(1206): recvConnackProc error,result = -35

[inf] _network_ssl_disconnect(519): ssl_disconnect

[err] iotx_mc_connect(2027): wait connect ACK timeout, or receive a ACK indicating error!

[inf] HAL_SSL_Destroy(535): handle is NULL

[inf] iotx_mc_disconnect(2129): mqtt disconnect!

[inf] iotx_mc_release(2175): mqtt release!

mqtt_client|221 :: MQTT construct failed

[err] LITE_dump_malloc_free_stats(594): WITH_MEM_STATS = 0

I (46505) MQTT: MQTT client example end, free heap size:52864

I (46514) MQTT: MQTT client example begin, free heap size:52864`

请问出现以上错误原因是什么？

**Comment by Shaco-Ma** [comment]
[err] iotx_mc_wait_CONNACK(1206): recvConnackProc error,result = -35
这个是用户名和密码有问题的错误提示哦

**Comment by Eavo** [comment]
请问问题是否解决了？

**Comment by donny681** [comment]
已经解决了。是填入配置参数错误。

**Comment by wollir** [comment]
> 已经解决了。是填入配置参数错误。

同样的问题，请问是哪里的配置参数错了呢
