### ISSUE TITLE
error when run 'make aliyun' command, gsed: command not found ,on mac

### ISSUE THREAD

**Issue by Fick707** [espressif/esp-aliyun#80]
分支：master
操作系统：macOS Majave

gsed应该是windows下的sed命令吧？
能支持mac下开发吗？

**Comment by Fick707** [comment]
把脚本中gsed的地方换成了sed之后，命令能跑了，但是好像litiot_sdk.a并没有啊。不知道怎么玩了。

希望在mqtt示例程序的readme.md文件中，写一下傻瓜式的操作步骤。

**Comment by Fick707** [comment]
命令详细的日志如下，不知道这个命令结果是对的还是错的。

➜  mqtt git:(master) ✗ make aliyun
Toolchain path: /Users/songfei/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
GENCONFIG
config esp32 platform...
SELECTED CONFIGURATION:

VENDOR :   espressif
MODEL  :   esp


CONFIGURE .............................. [sample]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/cmp]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/coap]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/cota]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/dm]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/fota]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/http]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/log]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/mqtt]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/ota]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/platform]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/sdk-tests]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/shadow]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/subdev]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/system]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/tfs]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/tls]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
CONFIGURE .............................. [src/utils]
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'

BUILDING WITH EXISTING CONFIGURATION:

VENDOR :   espressif
MODEL  :   esp

Components: 

[..] o sample                      [..]sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
. sample                                          
[..] o src/cmp                     [..]sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
. src/cmp                                          
. src/fota                                          
. src/cota                                          
. src/sdk-tests                                          
. src/shadow                                          
. src/platform                                          
. src/utils                                          
. src/subdev                                          
. src/system                                          
. src/tfs                                           
. src/tls                                           
. src/http                                          
. src/dm                                            
. src/log                                           
. src/ota                                           
. src/mqtt                                          
[..] o src/coap                    [..]sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
. src/coap                                          

sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
sed: 1: "/Users/songfei/esp/esp- ...": bad flag in substitute command: 'n'
[AR] libiot_sdk.a               <=

**Comment by Fick707** [comment]
感觉是将gsed换成sed命令后，很多地方都没有正确执行。

**Comment by Eavo** [comment]
mac 下编译错误，请参考 #72 修改，之后会更新到 readme 中。

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
