### ISSUE TITLE
官方会不会考虑升级aliyunSDK 到  2.2.1 版本？

### ISSUE THREAD

**Issue by titawork** [espressif/esp-aliyun#83]

**Comment by hqchen118** [comment]
这个aliyunSDK是哪个版本？

**Comment by Eavo** [comment]
当前为 aliyun v2.10 版本，正在规划 aliyun 的版本升级，谢谢支持和关注。

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
