### ISSUE TITLE
该仓库只适用于单核吗？配置成双核，烧写到ESP32上，一直复位。

### ISSUE THREAD

**Issue by hqchen118** [espressif/esp-aliyun#85]

**Comment by Eavo** [comment]
经过验证，双核的配置是可以工作的。

双核配置：
![fw2ue j imodr 8lu4vgo](https://user-images.githubusercontent.com/31977734/50428808-4dfdd000-08f5-11e9-8e3d-0c4ec0da8cfe.jpg)

单核配置：
![3g fd6y 0bxh6op k88 t](https://user-images.githubusercontent.com/31977734/50428816-581fce80-08f5-11e9-8ac1-097987fb8fdc.jpg)
