### ISSUE TITLE
[CLDGIT-1]阿里云v2.10 内存泄露问题

### ISSUE THREAD

**Issue by wanghui0574xs** [espressif/esp-aliyun#86]
由于阿里云 sdk2.10存在问题, 是否升级支持到阿里云 sdk2.30

**Comment by Eavo** [comment]
您好，从我们当前在 ESP32 下挂机测试的表现来看，SDK v2.10 还是比较稳定的。下一步我们计划先修复 ESP8266 based on aliyun v2.10 上的问题，之后再规划升级 aliyun 版本。谢谢关注和支持。

**Comment by wanghui0574xs** [comment]
阿里工程师说v2.10在mqtt重连的时候有内存泄露的bug。不知你们是否有处理过？我挂机测试有时候一小时里有3-4次因为-30384接收错误而mqtt重连，偶尔一次-78的发送错误而mqtt重连。而且发送没有设定超时，这个-78错误要等很久才出来。

**Comment by wanghui0574xs** [comment]
> 您好，从我们当前在 ESP32 下挂机测试的表现来看，SDK v2.10 还是比较稳定的。下一步我们计划先修复 ESP8266 based on aliyun v2.10 上的问题，之后再规划升级 aliyun 版本。谢谢关注和支持。

阿里工程师说v2.10在mqtt重连的时候有内存泄露的bug。不知你们是否有处理过？我挂机测试有时候一小时里有3-4次因为-30384接收错误而mqtt重连，偶尔一次-78的发送错误而mqtt重连。而且发送没有设定超时，这个-78错误要等很久才出来。

**Comment by Eavo** [comment]
请问您是使用的 ESP32 还是 ESP8266？哪个版本的 IDF/SDK？是否有 log 可以给我们看一下？

**Comment by wanghui0574xs** [comment]
> 请问您是使用的 ESP32 还是 ESP8266？哪个版本的 IDF/SDK？是否有 log 可以给我们看一下？

在ESP8266上.
![image](https://user-images.githubusercontent.com/11225683/50411384-6b219880-083a-11e9-86d6-5bb20afae620.png)

发生发送-78错误
inf] _network_ssl_write(499): ssl write fail, code=-78, str=
[err] iotx_mc_publish(1469): MQTTPublish is error, rc = -14
[err] iotx_mc_keepalive(1870): network is disconnected!
mqtt_event_handle|314 :: MQTT disconnect.
mbedtls_net_send:-1, need:128
断开ssl连接
[inf] _network_ssl_disconnect(524): ssl_disconnect
[dbg] iotx_mc_cycle(1224): state = 4
I (16740650) MqttTask: Unsubscribe book
[err] iotx_mc_unsubscribe(1408): mqtt client state is error,state = 4
[inf] iotx_mc_handle_reconnect(2071): Waiting to reconnect...
[inf] iotx_mc_handle_reconnect(2077): start to reconnect
进行重新连接, 返回失败-0x4290
[inf] _TLSConnectNetwork(414): failed  ! mbedtls_ssl_handshake returned -0x4290
[inf] _network_ssl_disconnect(524): ssl_disconnect
[inf] HAL_SSL_Destroy(540): handle is NULL
[err] iotx_mc_connect(2000): TCP or TLS Connection failed
[err] iotx_mc_attempt_reconnect(2054): run iotx_mqtt_connect() error!
[err] iotx_mc_handle_reconnect(2105): mqtt reconnect failed rc = -28
[dbg] iotx_mc_keepalive(1858): reconnect network fail, rc = -28
[dbg] iotx_mc_cycle(1224): state = 4

[inf] HAL_SSL_Destroy(540): handle is NULL
[inf] iotx_mc_disconnect(2128): mqtt disconnect!

**Comment by Eavo** [comment]
看着确实是像内存泄露，建议重连时，打印下剩余内存信息
![ae3psk m11ljf k0hb dr](https://user-images.githubusercontent.com/31977734/50415846-581dc100-0858-11e9-922a-742978da0ef6.jpg)

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88
