### ISSUE TITLE
使用阿里云v2.30的库时链接错误error adding symbols: Archive has no index; run ranlib to add one

### ISSUE THREAD

**Issue by wanghui0574xs** [espressif/esp-aliyun#87]
使用阿里云v2.30的库时链接错误error adding symbols: Archive has no index; run ranlib to add one

**Comment by Eavo** [comment]
您好，如上一条回复，我们当前还不支持 aliyun v2.30，谢谢。

**Comment by Eavo** [comment]
您好，SDK 已更新，支持 aliyun v2.30，详情请查阅：https://github.com/espressif/esp-aliyun/issues/88

**Comment by simonliu009** [comment]
我也遇到这个问题
``...esp-aliyun/iotkit-embedded/output/release/lib/libiot_sdk.a: error adding symbols: Archive has no index; run ranlib to add one``
ESP8266_RTOS_SDK已经切换到``5df0b1d71``分支
iotkit-embedded分别尝试了``V2.3.0``分支和``master``分支
