### ISSUE TITLE
最后make出现错误：cannot find -liot_sdk

### ISSUE THREAD

**Issue by yhg004** [espressif/esp-aliyun#89]
LD build/mqtt_example.elf
/esp32/crossTools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot find -liot_sdk

**Comment by ustccw** [comment]
请参考 README.md 先编译 libiot_sdk.a

**Comment by Eavo** [comment]
如果问题还未解决，可以随时 reopen。谢谢支持。
