### ISSUE TITLE
编译esp-aliyun/examples/mqtt_example提示fatal error: iot_import.h

### ISSUE THREAD

**Issue by simonliu009** [espressif/esp-aliyun#90]
~/Espressif/ESP8266/freeRTOS/myProjects/esp-aliyun/platform/hal/os/espressif/HAL_OS_espressif.c:34:24: fatal error: iot_import.h: No such file or directory
compilation terminated.
make[1]: *** [platform/hal/os/espressif/HAL_OS_espressif.o] Error 1
make: *** [component-esp-aliyun-build] Error 2

**Comment by ustccw** [comment]
请按照 README.md 先编译 libiot_sdk.a

**Comment by simonliu009** [comment]
谢谢。
当时没注意这个目录是外部链接，从这里git clone 看到目录是空的所以就跳过去了。
但是还有其他编译问题，我还是贴到相同的issue后面吧。这个先close了。

**Comment by wanghui0574xs** [comment]
> 请按照 README.md 先编译 libiot_sdk.a

编译libiot_sdk.a有没有详细说明, 以前只要make aliyun 现在都找不到怎么编译了
