### ISSUE TITLE
mac下编译aliyun v2.30仍然提示Archive has no index; run ranlib to add one

### ISSUE THREAD

**Issue by simonliu009** [espressif/esp-aliyun#91]
我在mac下编译aliyun v2.30仍然提示``Archive has no index; run ranlib to add one``
错误信息如下： 
```
/Users/simonliu/Espressif/ESP8266/freeRTOS/myProjects/esp-aliyun/iotkit-embedded/output/release/lib/libiot_sdk.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
make: *** [/Users/simonliu/Espressif/ESP8266/freeRTOS/myProjects/esp-aliyun/examples/mqtt_example/build/mqtt_example.elf] Error 1
```
``~/Espressif/ESP8266/freeRTOS/myProjects/esp-aliyun/iotkit-embedded/output/release/lib/libiot_sdk.a``已经生成了
freeRTOS已经切换到`5df0b1d`分支
iotkit-embedded分别尝试了`V2.3.0`分支和`master`分支都是相同的错误。

OS：macOS Mojave (10.14.3)
freeRTOS version：branch `5df0b1d`
iotkit-embedded version:Both `V2.3.0` and `master` branches are tested.

**Comment by ustccw** [comment]
@simonliu009 暂时还不支持在 mac 上开发, 后续会支持此.

**Comment by Eavo** [comment]
如果问题还未解决，可以随时 reopen。谢谢支持。
