### ISSUE TITLE
编译 SDK ，生成 libiot_sdk.a，make编译时错误

### ISSUE THREAD

**Issue by XJGpy** [espressif/esp-aliyun#92]
如题，使用的esp32平台，当复制了文件修改后，执行make 时 出现这样的问题：
xtensa-esp32-elf-gcc: error: unrecognized command line option '-ESPOS_FOR_ESP32'

这个如何解决？ @projectgus @kedars @igrr @ameyinamdar @Spritetm

**Comment by projectgus** [comment]
@ustccw Can you help with this, please?

**Comment by ustccw** [comment]
@XJGpy 不应该去掉 `-D` 属性, 这代表宏定义, 因此和 readme.md 中描述一样, 改为 `-DESPOS_FOR_ESP32`

**Comment by Eavo** [comment]
如果问题还未解决，可以随时 reopen。谢谢支持。
